# App image for production/real environment run
ARG NODE_VERSION

FROM node:${NODE_VERSION}-alpine AS development

WORKDIR /usr/src/app

COPY ./package*.json ./

RUN --mount=type=secret,id=npm_token \
    NPM_AUTH_TOKEN=$(cat /run/secrets/npm_token) && \
    npm config set //npm.pkg.github.com/:_authToken "$NPM_AUTH_TOKEN" && \
    npm ci && \
    npm config delete //npm.pkg.github.com/:_authToken && \
    rm -rf /root/.npm/_logs

COPY ../.. .

RUN npm run build

FROM node:${NODE_VERSION}-alpine as production

ARG NODE_ENV=production
ENV NODE_ENV=${NODE_ENV}
ENV NODE_PATH=/usr/src/app/build

WORKDIR /usr/src/app

COPY --chown=node:node package*.json ./

RUN --mount=type=secret,id=npm_token \
    NPM_AUTH_TOKEN=$(cat /run/secrets/npm_token) && \
    npm config set //npm.pkg.github.com/:_authToken "$NPM_AUTH_TOKEN" && \
    npm ci && \
    npm config delete //npm.pkg.github.com/:_authToken && \
    rm -rf /root/.npm/_logs

COPY --from=development --chown=node:node /usr/src/app/build ./build

USER node

CMD ["node", "build/index.js"]